FROM golang:latest as build

ADD . /src
WORKDIR /src
RUN mkdir -p dist && go build -o dist/example cmd/example/main.go 

FROM mcr.microsoft.com/powershell
COPY --from=build /src/dist/example /app/example
SHELL ["/usr/bin/pwsh", "-c"]
RUN if (!(Test-Path -Path $PROFILE)) { \
  New-Item -ItemType File -Path $PROFILE -Force \
}
RUN write-output '$env:PATH += [IO.Path]::PathSeparator + "/app"' >> $PROFILE
RUN write-output 'iex $(example hook powershell | Out-String)' >> $PROFILE